// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocal.proto

package com.randioo.randioo_server_base.net;

public final class Protocal {
  private Protocal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class PT extends
      com.google.protobuf.GeneratedMessage {
    // Use PT.newBuilder() to construct.
    private PT() {
      initFields();
    }
    private PT(boolean noInit) {}
    
    private static final PT defaultInstance;
    public static PT getDefaultInstance() {
      return defaultInstance;
    }
    
    public PT getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.randioo_server_base.net.Protocal.internal_static_com_randioo_randioo_server_base_net_PT_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.randioo_server_base.net.Protocal.internal_static_com_randioo_randioo_server_base_net_PT_fieldAccessorTable;
    }
    
    // required sint32 protocal = 1;
    public static final int PROTOCAL_FIELD_NUMBER = 1;
    private boolean hasProtocal;
    private int protocal_ = 0;
    public boolean hasProtocal() { return hasProtocal; }
    public int getProtocal() { return protocal_; }
    
    // required bytes data = 2;
    public static final int DATA_FIELD_NUMBER = 2;
    private boolean hasData;
    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasData() { return hasData; }
    public com.google.protobuf.ByteString getData() { return data_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasProtocal) return false;
      if (!hasData) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasProtocal()) {
        output.writeSInt32(1, getProtocal());
      }
      if (hasData()) {
        output.writeBytes(2, getData());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasProtocal()) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(1, getProtocal());
      }
      if (hasData()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getData());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.randioo_server_base.net.Protocal.PT parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.randioo_server_base.net.Protocal.PT parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.randioo_server_base.net.Protocal.PT parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.randioo_server_base.net.Protocal.PT parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.randioo_server_base.net.Protocal.PT parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.randioo_server_base.net.Protocal.PT parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.randioo_server_base.net.Protocal.PT parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.randioo_server_base.net.Protocal.PT parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.randioo_server_base.net.Protocal.PT parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.randioo_server_base.net.Protocal.PT parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.randioo_server_base.net.Protocal.PT prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.randioo_server_base.net.Protocal.PT result;
      
      // Construct using com.randioo.randioo_server_base.net.Protocal.PT.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.randioo_server_base.net.Protocal.PT();
        return builder;
      }
      
      protected com.randioo.randioo_server_base.net.Protocal.PT internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.randioo_server_base.net.Protocal.PT();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.randioo_server_base.net.Protocal.PT.getDescriptor();
      }
      
      public com.randioo.randioo_server_base.net.Protocal.PT getDefaultInstanceForType() {
        return com.randioo.randioo_server_base.net.Protocal.PT.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.randioo_server_base.net.Protocal.PT build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.randioo_server_base.net.Protocal.PT buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.randioo_server_base.net.Protocal.PT buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.randioo_server_base.net.Protocal.PT returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.randioo_server_base.net.Protocal.PT) {
          return mergeFrom((com.randioo.randioo_server_base.net.Protocal.PT)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.randioo_server_base.net.Protocal.PT other) {
        if (other == com.randioo.randioo_server_base.net.Protocal.PT.getDefaultInstance()) return this;
        if (other.hasProtocal()) {
          setProtocal(other.getProtocal());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setProtocal(input.readSInt32());
              break;
            }
            case 18: {
              setData(input.readBytes());
              break;
            }
          }
        }
      }
      
      
      // required sint32 protocal = 1;
      public boolean hasProtocal() {
        return result.hasProtocal();
      }
      public int getProtocal() {
        return result.getProtocal();
      }
      public Builder setProtocal(int value) {
        result.hasProtocal = true;
        result.protocal_ = value;
        return this;
      }
      public Builder clearProtocal() {
        result.hasProtocal = false;
        result.protocal_ = 0;
        return this;
      }
      
      // required bytes data = 2;
      public boolean hasData() {
        return result.hasData();
      }
      public com.google.protobuf.ByteString getData() {
        return result.getData();
      }
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasData = true;
        result.data_ = value;
        return this;
      }
      public Builder clearData() {
        result.hasData = false;
        result.data_ = getDefaultInstance().getData();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.randioo_server_base.net.PT)
    }
    
    static {
      defaultInstance = new PT(true);
      com.randioo.randioo_server_base.net.Protocal.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.randioo_server_base.net.PT)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_randioo_server_base_net_PT_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_randioo_server_base_net_PT_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016protocal.proto\022#com.randioo.randioo_se" +
      "rver_base.net\"$\n\002PT\022\020\n\010protocal\030\001 \002(\021\022\014\n" +
      "\004data\030\002 \002(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_randioo_randioo_server_base_net_PT_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_randioo_randioo_server_base_net_PT_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_randioo_server_base_net_PT_descriptor,
              new java.lang.String[] { "Protocal", "Data", },
              com.randioo.randioo_server_base.net.Protocal.PT.class,
              com.randioo.randioo_server_base.net.Protocal.PT.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
